### ISSUE TITLE
Is lib/ missing in npm?

### ISSUE THREAD

**Issue by azu** [textlint-rule/textlint-rule-ginger#2]
I try to install textlint-rule-ginger, and `lib/ginger.js` is not found.

> ReferenceError: Failed to load textlint's rule module: "ginger" is not found.
> See FAQ: https://github.com/textlint/textlint/blob/master/docs/faq/failed-to-load-textlints-module.md

I recommend that add `files` field to `packge.json` like [this](https://github.com/azu/textlint-rule-no-todo/blob/a560c745f280d2d0592dec108cded8661be7ff64/package.json#L17-L20).

Thanks

**Comment by nodaguti** [comment]
Oops, I forgot it.
Thank you for reporting!

**Comment by azu** [comment]
@nodaguti Thanks!
